name: Build & Deploy to Kubernetes

on:
  push:
    branches: ["main"]

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # 1️⃣ Login to Docker Hub
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 2️⃣ Build and Push Docker image
      - name: Build and Push
        run: |
          IMAGE=${{ secrets.DOCKER_REPO_CICD }}:${{ github.sha }}
          docker build -t $IMAGE .  
          docker push $IMAGE
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      # 3️⃣ Setup kubectl
      - uses: azure/setup-kubectl@v3

      # 4️⃣ Configure Kubernetes access
      - name: Configure kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config

      # 5️⃣ Deploy to Kubernetes
      - name: Deploy
        run: |
          kubectl set image deployment/myapp myapp=$IMAGE
          kubectl apply -f k8s/
